// <auto-generated />
using System;
using AplikasiCheckDimensi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikasiCheckDimensi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218035706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AplikasiCheckDimensi.Models.InputAktual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatatanOperator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grup")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPIC")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiDimensiA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiDimensiB")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter_SisiA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter_SisiAX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter_SisiAY")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter_SisiB")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter_SisiBX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiInnerDiameter_SisiBY")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter_SisiA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter_SisiAX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter_SisiAY")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter_SisiB")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter_SisiBX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiOuterDiameter_SisiBY")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiPanjang")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiRadius")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiSudut")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness_SisiA")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness_SisiAX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness_SisiAY")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness_SisiB")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness_SisiBX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiThickness_SisiBY")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NilaiTinggi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .HasColumnType("TEXT");

                    b.Property<int>("StandarDimensiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalInput")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StandarDimensiId");

                    b.ToTable("InputAktual");
                });

            modelBuilder.Entity("AplikasiCheckDimensi.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CT")
                        .HasColumnType("TEXT");

                    b.Property<string>("GambarCF")
                        .HasColumnType("TEXT");

                    b.Property<string>("GambarPacking")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifikasiItem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QtyPerBox")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandarCF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalInput")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeBox")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produk");
                });

            modelBuilder.Entity("AplikasiCheckDimensi.Models.StandarDimensi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DimensiA_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DimensiA_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DimensiB_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DimensiB_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerDiameter_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerDiameter_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerDiameter_SisiA_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerDiameter_SisiA_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerDiameter_SisiB_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InnerDiameter_SisiB_Min")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaDimensi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OuterDiameter_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OuterDiameter_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OuterDiameter_SisiA_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OuterDiameter_SisiA_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OuterDiameter_SisiB_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OuterDiameter_SisiB_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Panjang_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Panjang_Min")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdukId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Radius_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Radius_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Sudut_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Sudut_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness_SisiA_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness_SisiA_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness_SisiB_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Thickness_SisiB_Min")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tinggi_Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tinggi_Min")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProdukId");

                    b.ToTable("StandarDimensi");
                });

            modelBuilder.Entity("AplikasiCheckDimensi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalDibuat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AplikasiCheckDimensi.Models.InputAktual", b =>
                {
                    b.HasOne("AplikasiCheckDimensi.Models.StandarDimensi", "StandarDimensi")
                        .WithMany("InputAktualls")
                        .HasForeignKey("StandarDimensiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandarDimensi");
                });

            modelBuilder.Entity("AplikasiCheckDimensi.Models.StandarDimensi", b =>
                {
                    b.HasOne("AplikasiCheckDimensi.Models.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("AplikasiCheckDimensi.Models.StandarDimensi", b =>
                {
                    b.Navigation("InputAktualls");
                });
#pragma warning restore 612, 618
        }
    }
}
